import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import Background from "./components/Background";
import "./globals.css";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-montserrat",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased select-none">
      <body className={`${montserrat.className} min-h-full flex flex-col`}>
        <div className="relative z-10 min-h-full flex-1">
          <Background isVisible={true} />
          {children}
        </div>
      </body>
    </html>
  );
}
